### ISSUE TITLE
Karte https://www.farmshops.eu/ funktioniert nicht

### ISSUE THREAD

**Issue by gregnix** [CodeforKarlsruhe/farmshops.eu#94]
Funktioniert nicht:
https://www.farmshops.eu/

Funktioniert
https://farmshops.eu/

von: https://github.com/CodeforKarlsruhe/farmshops.eu
Webseite: https://www.farmshops.eu/
Mirror: https://codeforkarlsruhe.github.io/farmshops.eu

mfg
Gregor

**Comment by stefangrotz** [comment]
Danke für den Hinweis.
Es sollte eigentlich damit gelöst sein: 9f98320

**Comment by stefangrotz** [comment]
gefixt über den DNS record, danke für den Hinweis!
